Update CI Workflows  (#204)
* test ci

* update ci

* fix ci

* remove telegram notification

* update metadata

* update ci

* update cache

* fix ruby version

* remove subdir fastlane

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,6 +5,9 @@ on:
     branches:
       - ci
       - develop
+  pull_request:
+    branches:
+      - master
 
 env:
   LANG: en_US.UTF-8
@@ -56,6 +59,12 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
+      - name: Setup Ruby
+        uses: actions/setup-ruby@v1
+        with:
+          ruby-version: 2.6
+          bundler-cache: true
+
       - name: Set up Cloud SDK
         uses: google-github-actions/setup-gcloud@master
         with:
@@ -86,12 +95,33 @@ jobs:
         uses: maierj/fastlane-action@v2.0.1
         with:
           lane: all
+          bundle-install-path: "vendor/bundle"
 
       - name: Deploy to OTA Server
         shell: bash
         run: |
           # ota configure variable
-          OTA_URL="${{ secrets.OTA_URL }}"
+          DEV_OTA_URL="${{ secrets.DEV_OTA_URL }}"
+          STG_OTA_URL="${{ secrets.STG_OTA_URL }}"
+
+          OTA_URL="$DEV_OTA_URL"
+          APP_SUFFIX="Develop"
+
+          # prepare metadata
+          REPO_URL="https://github.com/${{ github.repository }}" 
+          METADATA="{\"repo\": \"$REPO_URL\", \"commit\": \"$GITHUB_SHA\"}"
+
+          # deploy to Staging OTA server if event 
+          # that trigger workflow is `pull_request`
+          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
+            OTA_URL="$STG_OTA_URL"
+            APP_SUFFIX="Staging"
+
+            # extract PR number
+            PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+            METADATA="{\"repo\": \"$REPO_URL\", \"pr_number\": \"$PR_NUMBER\"}"
+          fi
+
           OTA_USERNAME="${{ secrets.OTA_USERNAME }}"
           OTA_SECRET="${{ secrets.OTA_SECRET }}"
 
@@ -99,7 +129,7 @@ jobs:
           OBJECT_ID=$(curl -sSfL -F "file=@./archives/KyberSwap.ipa" -u "$OTA_USERNAME:$OTA_SECRET" $OTA_URL/api/v1/storages/upload | jq -r .object_id)
 
           # set default app name
-          APP_NAME="Kyber Swap: Develop"
+          APP_NAME="Kyber Swap: $APP_SUFFIX"
 
           # extract build 
           BUILD=$(cat KyberNetwork.xcodeproj/project.pbxproj | grep -m1 'CURRENT_PROJECT_VERSION' | cut -d'=' -f2 | tr -d ';' | tr -d ' ')
@@ -113,9 +143,11 @@ jobs:
           CODE=$(curl -sSfL -XPOST -H "Content-Type: application/json" \
                   -o /dev/null -w "%{http_code}" \
                   -u "$OTA_USERNAME:$OTA_SECRET" \
-                  -d "{\"bundle_id\": \"$APPLE_BUNDLE_ID\", \"app_name\": \"$APP_NAME\", \"object_id\": $OBJECT_ID, \"build\": $BUILD, \"version\": \"$VERSION\", \"metadata\": {\"commit\": \"${{ github.sha }}\", \"repo\": \"https://github.com/${{ github.repository }}\"}}" \
+                  -d "{\"bundle_id\": \"$APPLE_BUNDLE_ID\", \"app_name\": \"$APP_NAME\", \"object_id\": $OBJECT_ID, \"build\": $BUILD, \"version\": \"$VERSION\", \"metadata\": $METADATA}" \
                   $OTA_URL/api/v1/profiles/ios)
-          [[ "$CODE" == 20* ]] || exit 1
+
+          # stop CI if upload to OTA server failed
+          [[ "$CODE" == 20* ]] || exit
 
       - name: Prepare bump build number
         run: |
@@ -127,3 +159,4 @@ jobs:
         uses: maierj/fastlane-action@v2.0.1
         with:
           lane: bump_build_number
+          bundle-install-path: 'vendor/bundle'
